version: '2'
services:
  halon-smtpd:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        HALON_REPO_USER: ${HALON_REPO_USER}
        HALON_REPO_PASS: ${HALON_REPO_PASS}
    volumes:
      - ../:/rabbitmq-consumer
      - ./smtpd/dist:/etc/halon
      - halon-spool:/var/spool/halon
  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672
volumes:
  halon-spool: